name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          runtime: nodejs12
          name: ${{ secrets.FUNCTION_NAME }}
          env_vars: BOT_TOKEN=${{ secrets.BOT_TOKEN }},VK_API_TOKEN=${{ secrets.VK_API_TOKEN }},PROJECT_ID=${{ secrets.PROJECT_ID }},REGION=${{ secrets.REGION }}
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.CI_KEY }}
          region: ${{ secrets.REGION }}

